### PART C: Incrase the number of epochs

#### Download and Clean Dataset

[Dataset Link](https://cocl.us/concrete_data)

The dataset is about the compressive strength of different samples of concrete based on the volumes of the different ingredients that were used to make them.

The predictors(ingredients) in the data of concrete strength include:

1. **Cement**

2. **Blast Furnace Slag**

3. **Fly Ash**

4. **Water**

5. **Superplasticizer**

6. **Coarse Aggregate**

7. **Fine Aggregate**

In [1]:
# Importing Numpy and Pandas Libraries to read the dataset

import pandas as pd
import numpy as np

In [2]:
# Reading the dataset into a pandas Dataframe

concrete_data = pd.read_csv("concrete_data.csv")
concrete_data.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

In [3]:
# Checking infomation about the DataSet

print(f"Datasetshape is: {concrete_data.shape}")
print(concrete_data.isnull().sum())
concrete_data.describe()

Datasetshape is: (1030, 9)
Cement                0
Blast Furnace Slag    0
Fly Ash               0
Water                 0
Superplasticizer      0
Coarse Aggregate      0
Fine Aggregate        0
Age                   0
Strength              0
dtype: int64

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
count,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000
mean,281.167864,73.895825,54.188350,181.567282,6.204660,972.918932,773.580485,45.662136,35.817961
std,104.506364,86.279342,63.997004,21.354219,5.973841,77.753954,80.175980,63.169912,16.705742
min,102.000000,0.000000,0.000000,121.800000,0.000000,801.000000,594.000000,1.000000,2.330000
25%,192.375000,0.000000,0.000000,164.900000,0.000000,932.000000,730.950000,7.000000,23.710000
50%,272.900000,22.000000,0.000000,185.000000,6.400000,968.000000,779.500000,28.000000,34.445000
75%,350.000000,142.950000,118.300000,192.000000,10.200000,1029.400000,824.000000,56.000000,46.135000
max,540.000000,359.400000,200.100000,247.000000,32.200000,1145.000000,992.600000,365.000000,82.600000

The data looks very clean and is ready to be used to build model


###### Split Dataset into Preditors and Target

In [5]:
concrete_data_columns = concrete_data.columns
predictors = concrete_data[concrete_data_columns[concrete_data_columns != 'Strength']] # all columns except Strength
target = concrete_data['Strength'] # Strength column

In [6]:
target.head()

0    79.99
1    61.89
2    40.27
3    41.05
4    44.30
Name: Strength, dtype: float64

###### Normalised Version of Data

In [7]:
predictors_norm = (predictors - predictors.mean()) / predictors.std()
predictors_norm.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,0.862735,-1.217079,-0.279597
1,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,1.055651,-1.217079,-0.279597
2,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,3.551340
3,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,5.055221
4,-0.790075,0.678079,-0.846733,0.488555,-1.038638,0.070492,0.647569,4.976069

In [8]:
n_cols = predictors_norm.shape[1]
n_cols

8

###### Import Keras

In [10]:
import tensorflow

from tensorflow import keras

from keras.models import Sequential
from keras.layers import Dense

In [11]:
# define regression model
def regression_model():
    # create model
    model = Sequential()
    model.add(Dense(10, activation='relu', input_shape=(n_cols,)))
    model.add(Dense(1))
    
    # compile model
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

In [12]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(predictors_norm, target, test_size=0.3, random_state=42)

###### Train and Test Network

In [13]:
# Build the model

model = regression_model()

## PART C: Incrase the number of epochs (5 marks)

- **Repeat Part B but use 100 epochs this time for training.**

**How does the mean of the mean squared errors compare to that from Step B?**

In [14]:
# fit the model

model.fit(X_train, y_train, epochs=100, verbose=2)

Epoch 1/100
23/23 - 1s - loss: 1549.2274 - 1s/epoch - 47ms/step
Epoch 2/100
23/23 - 0s - loss: 1531.5012 - 55ms/epoch - 2ms/step
Epoch 3/100
23/23 - 0s - loss: 1513.5525 - 57ms/epoch - 2ms/step
Epoch 4/100
23/23 - 0s - loss: 1494.7628 - 57ms/epoch - 2ms/step
Epoch 5/100
23/23 - 0s - loss: 1475.5527 - 57ms/epoch - 2ms/step
Epoch 6/100
23/23 - 0s - loss: 1455.0990 - 61ms/epoch - 3ms/step
Epoch 7/100
23/23 - 0s - loss: 1434.2142 - 66ms/epoch - 3ms/step
Epoch 8/100
23/23 - 0s - loss: 1412.1907 - 76ms/epoch - 3ms/step
Epoch 9/100
23/23 - 0s - loss: 1389.6721 - 68ms/epoch - 3ms/step
Epoch 10/100
23/23 - 0s - loss: 1365.7859 - 62ms/epoch - 3ms/step
Epoch 11/100
23/23 - 0s - loss: 1341.0283 - 56ms/epoch - 2ms/step
Epoch 12/100
23/23 - 0s - loss: 1315.4617 - 48ms/epoch - 2ms/step
Epoch 13/100
23/23 - 0s - loss: 1288.6793 - 62ms/epoch - 3ms/step
Epoch 14/100
23/23 - 0s - loss: 1260.9147 - 52ms/epoch - 2ms/step
Epoch 15/100
23/23 - 0s - loss: 1232.4102 - 55ms/epoch - 2ms/step
Epoch 16/100
23/23 - 0s - loss: 1203.4513 - 60ms/epoch - 3ms/step
Epoch 17/100
23/23 - 0s - loss: 1172.5121 - 61ms/epoch - 3ms/step
Epoch 18/100
23/23 - 0s - loss: 1141.6923 - 56ms/epoch - 2ms/step
Epoch 19/100
23/23 - 0s - loss: 1109.6371 - 54ms/epoch - 2ms/step
Epoch 20/100
23/23 - 0s - loss: 1077.3419 - 67ms/epoch - 3ms/step
Epoch 21/100
23/23 - 0s - loss: 1044.2714 - 79ms/epoch - 3ms/step
Epoch 22/100
23/23 - 0s - loss: 1010.9542 - 70ms/epoch - 3ms/step
Epoch 23/100
23/23 - 0s - loss: 977.5053 - 67ms/epoch - 3ms/step
Epoch 24/100
23/23 - 0s - loss: 943.9690 - 76ms/epoch - 3ms/step
Epoch 25/100
23/23 - 0s - loss: 911.5128 - 54ms/epoch - 2ms/step
Epoch 26/100
23/23 - 0s - loss: 878.1151 - 76ms/epoch - 3ms/step
Epoch 27/100
23/23 - 0s - loss: 845.9755 - 78ms/epoch - 3ms/step
Epoch 28/100
23/23 - 0s - loss: 813.9030 - 77ms/epoch - 3ms/step
Epoch 29/100
23/23 - 0s - loss: 782.7573 - 77ms/epoch - 3ms/step
Epoch 30/100
23/23 - 0s - loss: 752.1190 - 54ms/epoch - 2ms/step
Epoch 31/100
23/23 - 0s - loss: 721.7277 - 65ms/epoch - 3ms/step
Epoch 32/100
23/23 - 0s - loss: 692.7670 - 58ms/epoch - 3ms/step
Epoch 33/100
23/23 - 0s - loss: 663.6548 - 73ms/epoch - 3ms/step
Epoch 34/100
23/23 - 0s - loss: 635.8343 - 58ms/epoch - 3ms/step
Epoch 35/100
23/23 - 0s - loss: 609.7075 - 76ms/epoch - 3ms/step
Epoch 36/100
23/23 - 0s - loss: 583.5914 - 76ms/epoch - 3ms/step
Epoch 37/100
23/23 - 0s - loss: 559.2130 - 50ms/epoch - 2ms/step
Epoch 38/100
23/23 - 0s - loss: 535.2420 - 81ms/epoch - 4ms/step
Epoch 39/100
23/23 - 0s - loss: 512.7524 - 58ms/epoch - 3ms/step
Epoch 40/100
23/23 - 0s - loss: 490.2784 - 71ms/epoch - 3ms/step
Epoch 41/100
23/23 - 0s - loss: 469.4452 - 61ms/epoch - 3ms/step
Epoch 42/100
23/23 - 0s - loss: 449.2498 - 55ms/epoch - 2ms/step
Epoch 43/100
23/23 - 0s - loss: 430.2836 - 80ms/epoch - 3ms/step
Epoch 44/100
23/23 - 0s - loss: 412.1641 - 62ms/epoch - 3ms/step
Epoch 45/100
23/23 - 0s - loss: 395.2292 - 72ms/epoch - 3ms/step
Epoch 46/100
23/23 - 0s - loss: 378.6768 - 75ms/epoch - 3ms/step
Epoch 47/100
23/23 - 0s - loss: 363.1005 - 62ms/epoch - 3ms/step
Epoch 48/100
23/23 - 0s - loss: 348.9576 - 73ms/epoch - 3ms/step
Epoch 49/100
23/23 - 0s - loss: 335.3489 - 70ms/epoch - 3ms/step
Epoch 50/100
23/23 - 0s - loss: 322.3762 - 62ms/epoch - 3ms/step
Epoch 51/100
23/23 - 0s - loss: 310.4202 - 62ms/epoch - 3ms/step
Epoch 52/100
23/23 - 0s - loss: 299.2478 - 53ms/epoch - 2ms/step
Epoch 53/100
23/23 - 0s - loss: 288.8791 - 61ms/epoch - 3ms/step
Epoch 54/100
23/23 - 0s - loss: 278.9779 - 49ms/epoch - 2ms/step
Epoch 55/100
23/23 - 0s - loss: 270.1821 - 45ms/epoch - 2ms/step
Epoch 56/100
23/23 - 0s - loss: 261.6562 - 54ms/epoch - 2ms/step
Epoch 57/100
23/23 - 0s - loss: 254.0239 - 56ms/epoch - 2ms/step
Epoch 58/100
23/23 - 0s - loss: 246.8388 - 55ms/epoch - 2ms/step
Epoch 59/100
23/23 - 0s - loss: 240.3165 - 58ms/epoch - 3ms/step
Epoch 60/100
23/23 - 0s - loss: 234.2855 - 59ms/epoch - 3ms/step
Epoch 61/100
23/23 - 0s - loss: 228.7110 - 44ms/epoch - 2ms/step
Epoch 62/100
23/23 - 0s - loss: 223.4884 - 42ms/epoch - 2ms/step
Epoch 63/100
23/23 - 0s - loss: 218.8250 - 60ms/epoch - 3ms/step
Epoch 64/100
23/23 - 0s - loss: 214.5960 - 66ms/epoch - 3ms/step
Epoch 65/100
23/23 - 0s - loss: 210.7067 - 61ms/epoch - 3ms/step
Epoch 66/100
23/23 - 0s - loss: 207.0106 - 65ms/epoch - 3ms/step
Epoch 67/100
23/23 - 0s - loss: 203.7538 - 62ms/epoch - 3ms/step
Epoch 68/100
23/23 - 0s - loss: 200.8165 - 55ms/epoch - 2ms/step
Epoch 69/100
23/23 - 0s - loss: 197.9155 - 57ms/epoch - 2ms/step
Epoch 70/100
23/23 - 0s - loss: 195.3311 - 66ms/epoch - 3ms/step
Epoch 71/100
23/23 - 0s - loss: 192.9963 - 55ms/epoch - 2ms/step
Epoch 72/100
23/23 - 0s - loss: 190.7333 - 56ms/epoch - 2ms/step
Epoch 73/100
23/23 - 0s - loss: 188.5054 - 57ms/epoch - 2ms/step
Epoch 74/100
23/23 - 0s - loss: 186.6083 - 57ms/epoch - 2ms/step
Epoch 75/100
23/23 - 0s - loss: 184.8423 - 55ms/epoch - 2ms/step
Epoch 76/100
23/23 - 0s - loss: 183.0567 - 54ms/epoch - 2ms/step
Epoch 77/100
23/23 - 0s - loss: 181.4469 - 48ms/epoch - 2ms/step
Epoch 78/100
23/23 - 0s - loss: 180.0325 - 59ms/epoch - 3ms/step
Epoch 79/100
23/23 - 0s - loss: 178.4881 - 53ms/epoch - 2ms/step
Epoch 80/100
23/23 - 0s - loss: 177.1711 - 60ms/epoch - 3ms/step
Epoch 81/100
23/23 - 0s - loss: 175.8586 - 53ms/epoch - 2ms/step
Epoch 82/100
23/23 - 0s - loss: 174.7150 - 60ms/epoch - 3ms/step
Epoch 83/100
23/23 - 0s - loss: 173.5144 - 55ms/epoch - 2ms/step
Epoch 84/100
23/23 - 0s - loss: 172.3589 - 57ms/epoch - 2ms/step
Epoch 85/100
23/23 - 0s - loss: 171.3236 - 54ms/epoch - 2ms/step
Epoch 86/100
23/23 - 0s - loss: 170.2372 - 61ms/epoch - 3ms/step
Epoch 87/100
23/23 - 0s - loss: 169.2242 - 58ms/epoch - 3ms/step
Epoch 88/100
23/23 - 0s - loss: 168.2135 - 59ms/epoch - 3ms/step
Epoch 89/100
23/23 - 0s - loss: 167.3293 - 66ms/epoch - 3ms/step
Epoch 90/100
23/23 - 0s - loss: 166.3436 - 64ms/epoch - 3ms/step
Epoch 91/100
23/23 - 0s - loss: 165.4367 - 68ms/epoch - 3ms/step
Epoch 92/100
23/23 - 0s - loss: 164.5514 - 51ms/epoch - 2ms/step
Epoch 93/100
23/23 - 0s - loss: 163.6216 - 60ms/epoch - 3ms/step
Epoch 94/100
23/23 - 0s - loss: 162.7506 - 68ms/epoch - 3ms/step
Epoch 95/100
23/23 - 0s - loss: 161.8686 - 60ms/epoch - 3ms/step
Epoch 96/100
23/23 - 0s - loss: 160.9541 - 69ms/epoch - 3ms/step
Epoch 97/100
23/23 - 0s - loss: 160.1398 - 49ms/epoch - 2ms/step
Epoch 98/100
23/23 - 0s - loss: 159.2249 - 49ms/epoch - 2ms/step
Epoch 99/100
23/23 - 0s - loss: 158.4303 - 68ms/epoch - 3ms/step
Epoch 100/100
23/23 - 0s - loss: 157.6216 - 60ms/epoch - 3ms/step

Next, we need to evaluate the model on the test data.

In [15]:
loss_val = model.evaluate(X_test, y_test)
y_pred = model.predict(X_test)
loss_val

10/10 [==============================] - 0s 2ms/step - loss: 154.6465
10/10 [==============================] - 0s 2ms/step

154.64654541015625

Now we need to compute the mean squared error between the predicted concrete strength and the actual concrete strength.

Let's import the mean_squared_error function from Scikit-learn.

In [16]:
from sklearn.metrics import mean_squared_error

mean_square_error = mean_squared_error(y_test, y_pred)
mean = np.mean(mean_square_error)
standard_deviation = np.std(mean_square_error)
print(mean, standard_deviation)

154.64654947767298 0.0

Create a list of 50 mean squared errors and report mean and the standard deviation of the mean squared errors.

In [17]:
total_mean_squared_errors = 50
epochs = 100
mean_squared_errors = []
for i in range(0, total_mean_squared_errors):
    X_train, X_test, y_train, y_test = train_test_split(predictors_norm, target, test_size=0.3, random_state=i)
    model.fit(X_train, y_train, epochs=epochs, verbose=0)
    MSE = model.evaluate(X_test, y_test, verbose=0)
    print("MSE "+str(i+1)+": "+str(MSE))
    y_pred = model.predict(X_test)
    mean_square_error = mean_squared_error(y_test, y_pred)
    mean_squared_errors.append(mean_square_error)

mean_squared_errors = np.array(mean_squared_errors)
mean = np.mean(mean_squared_errors)
standard_deviation = np.std(mean_squared_errors)

print('\n')
print("Below is the mean and standard deviation of " +str(total_mean_squared_errors) + " mean squared errors with normalized data. Total number of epochs for each training is: " +str(epochs) + "\n")
print("Mean: "+str(mean))
print("Standard Deviation: "+str(standard_deviation))

MSE 1: 73.36727905273438
10/10 [==============================] - 0s 3ms/step
MSE 2: 69.91366577148438
10/10 [==============================] - 0s 3ms/step
MSE 3: 40.832733154296875
10/10 [==============================] - 0s 3ms/step
MSE 4: 42.681121826171875
10/10 [==============================] - 0s 2ms/step
MSE 5: 43.94369888305664
10/10 [==============================] - 0s 2ms/step
MSE 6: 44.93804168701172
10/10 [==============================] - 0s 2ms/step
MSE 7: 45.662193298339844
10/10 [==============================] - 0s 3ms/step
MSE 8: 34.23462677001953
10/10 [==============================] - 0s 2ms/step
MSE 9: 38.76713943481445
10/10 [==============================] - 0s 2ms/step
MSE 10: 38.632415771484375
10/10 [==============================] - 0s 3ms/step
MSE 11: 37.342342376708984
10/10 [==============================] - 0s 3ms/step
MSE 12: 35.85148239135742
10/10 [==============================] - 0s 2ms/step
MSE 13: 41.809329986572266
10/10 [==============================] - 0s 2ms/step
MSE 14: 43.283809661865234
10/10 [==============================] - 0s 2ms/step
MSE 15: 33.97501754760742
10/10 [==============================] - 0s 2ms/step
MSE 16: 30.650592803955078
10/10 [==============================] - 0s 2ms/step
MSE 17: 36.559059143066406
10/10 [==============================] - 0s 2ms/step
MSE 18: 35.90058135986328
10/10 [==============================] - 0s 2ms/step
MSE 19: 36.24504089355469
10/10 [==============================] - 0s 2ms/step
MSE 20: 35.655303955078125
10/10 [==============================] - 0s 2ms/step
MSE 21: 35.79656982421875
10/10 [==============================] - 0s 2ms/step
MSE 22: 30.951562881469727
10/10 [==============================] - 0s 2ms/step
MSE 23: 31.730566024780273
10/10 [==============================] - 0s 2ms/step
MSE 24: 30.43558120727539
10/10 [==============================] - 0s 2ms/step
MSE 25: 33.01444625854492
10/10 [==============================] - 0s 2ms/step
MSE 26: 34.875396728515625
10/10 [==============================] - 0s 3ms/step
MSE 27: 31.06159210205078
10/10 [==============================] - 0s 2ms/step
MSE 28: 32.93156051635742
10/10 [==============================] - 0s 2ms/step
MSE 29: 35.76521301269531
10/10 [==============================] - 0s 2ms/step
MSE 30: 34.47502136230469
10/10 [==============================] - 0s 3ms/step
MSE 31: 29.951499938964844
10/10 [==============================] - 0s 2ms/step
MSE 32: 29.04045295715332
10/10 [==============================] - 0s 2ms/step
MSE 33: 29.560293197631836
10/10 [==============================] - 0s 2ms/step
MSE 34: 31.33584976196289
10/10 [==============================] - 0s 2ms/step
MSE 35: 33.22304153442383
10/10 [==============================] - 0s 2ms/step
MSE 36: 39.587284088134766
10/10 [==============================] - 0s 2ms/step
MSE 37: 27.794214248657227
10/10 [==============================] - 0s 2ms/step
MSE 38: 33.91962432861328
10/10 [==============================] - 0s 3ms/step
MSE 39: 34.7455940246582
10/10 [==============================] - 0s 3ms/step
MSE 40: 26.62814712524414
10/10 [==============================] - 0s 3ms/step
MSE 41: 35.17461013793945
10/10 [==============================] - 0s 2ms/step
MSE 42: 28.79409408569336
10/10 [==============================] - 0s 2ms/step
MSE 43: 34.30454635620117
10/10 [==============================] - 0s 2ms/step
MSE 44: 38.15655517578125
10/10 [==============================] - 0s 2ms/step
MSE 45: 35.831817626953125
10/10 [==============================] - 0s 4ms/step
MSE 46: 34.48283004760742
10/10 [==============================] - 0s 2ms/step
MSE 47: 34.088443756103516
10/10 [==============================] - 0s 3ms/step
MSE 48: 35.96485137939453
10/10 [==============================] - 0s 2ms/step
MSE 49: 34.86140823364258
10/10 [==============================] - 0s 2ms/step
MSE 50: 32.32994842529297
10/10 [==============================] - 0s 2ms/step


Below is the mean and standard deviation of 50 mean squared errors with normalized data. Total number of epochs for each training is: 100

Mean: 36.621161229691985
Standard Deviation: 8.370068512156795

###### Inference

- The mean of the mean squared errors is close to that found in part B (50 epochs)
- Increasing the number of epoch doesn't lead to better results